// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: internal/clusterstate/protocol/v1/cluster_state.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterState_Sync_FullMethodName  = "/dashboard.clusterstate.v1.ClusterState/Sync"
	ClusterState_Query_FullMethodName = "/dashboard.clusterstate.v1.ClusterState/Query"
	ClusterState_Watch_FullMethodName = "/dashboard.clusterstate.v1.ClusterState/Watch"
)

// ClusterStateClient is the client API for ClusterState service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The schema deliberately cannot represent Secret/ConfigMap data, kubeconfig,
// container env/envFrom, commands, args, volumes, or service-account tokens.
type ClusterStateClient interface {
	Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, ServerFrame], error)
	Query(ctx context.Context, in *ScreenQuery, opts ...grpc.CallOption) (*ScreenReply, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchFrame], error)
}

type clusterStateClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterStateClient(cc grpc.ClientConnInterface) ClusterStateClient {
	return &clusterStateClient{cc}
}

func (c *clusterStateClient) Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterState_ServiceDesc.Streams[0], ClusterState_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterState_SyncClient = grpc.BidiStreamingClient[AgentFrame, ServerFrame]

func (c *clusterStateClient) Query(ctx context.Context, in *ScreenQuery, opts ...grpc.CallOption) (*ScreenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenReply)
	err := c.cc.Invoke(ctx, ClusterState_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterStateClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterState_ServiceDesc.Streams[1], ClusterState_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterState_WatchClient = grpc.ServerStreamingClient[WatchFrame]

// ClusterStateServer is the server API for ClusterState service.
// All implementations must embed UnimplementedClusterStateServer
// for forward compatibility.
//
// The schema deliberately cannot represent Secret/ConfigMap data, kubeconfig,
// container env/envFrom, commands, args, volumes, or service-account tokens.
type ClusterStateServer interface {
	Sync(grpc.BidiStreamingServer[AgentFrame, ServerFrame]) error
	Query(context.Context, *ScreenQuery) (*ScreenReply, error)
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchFrame]) error
	mustEmbedUnimplementedClusterStateServer()
}

// UnimplementedClusterStateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterStateServer struct{}

func (UnimplementedClusterStateServer) Sync(grpc.BidiStreamingServer[AgentFrame, ServerFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedClusterStateServer) Query(context.Context, *ScreenQuery) (*ScreenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedClusterStateServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedClusterStateServer) mustEmbedUnimplementedClusterStateServer() {}
func (UnimplementedClusterStateServer) testEmbeddedByValue()                      {}

// UnsafeClusterStateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterStateServer will
// result in compilation errors.
type UnsafeClusterStateServer interface {
	mustEmbedUnimplementedClusterStateServer()
}

func RegisterClusterStateServer(s grpc.ServiceRegistrar, srv ClusterStateServer) {
	// If the following call pancis, it indicates UnimplementedClusterStateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterState_ServiceDesc, srv)
}

func _ClusterState_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterStateServer).Sync(&grpc.GenericServerStream[AgentFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterState_SyncServer = grpc.BidiStreamingServer[AgentFrame, ServerFrame]

func _ClusterState_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterStateServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterState_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterStateServer).Query(ctx, req.(*ScreenQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterState_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClusterStateServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterState_WatchServer = grpc.ServerStreamingServer[WatchFrame]

// ClusterState_ServiceDesc is the grpc.ServiceDesc for ClusterState service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterState_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.clusterstate.v1.ClusterState",
	HandlerType: (*ClusterStateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _ClusterState_Query_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _ClusterState_Sync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _ClusterState_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/clusterstate/protocol/v1/cluster_state.proto",
}
